### ISSUE TITLE
Bug - Placeholder text color

### ISSUE THREAD

**Issue by bahrens** [gcamp/GCPlaceholderTextView#1]
There is a bug in this code that happens when loading the text view and setting both the placeholder text and text properties.  This scenario causes the text to show up as light gray.  This is because the setting of text color only occurs on begin/end editing.  You should also override the setText in order to handle the colors appropriately.  Here is the fix that I did.
- (void) setText:(NSString *)text {
  super.text = text;
  if ([text isEqualToString:self.placeholder]) {
      self.textColor = [UIColor lightGrayColor];
  }
  else {
      self.textColor = self.realTextColor;
  }
  }

**Comment by gcamp** [comment]
Thanks bahrens!

Just pushed the changes!

If you want to participate to a project, you can http://help.github.com/fork-a-repo/ and make a pull request! That makes everything easier!

Thanks again!
