### ISSUE TITLE
Please add semantic version tags. 

### ISSUE THREAD

**Issue by dbgrandi** [gcamp/GCPlaceholderTextView#6]
I see that somebody has already added [`GCPlaceholderTextView`](https://github.com/CocoaPods/Specs/commit/2d11b63a26307f411b86291868b90096d06618b9) to the [CocoaPods](https://github.com/CocoaPods/CocoaPods) package manager repo.

CocoaPods is a tool for managing dependencies for OS X and iOS Xcode projects and provides a central repository for iOS/OS X libraries. This makes adding libraries to a project and updating them extremely easy and it will help users to resolve dependencies of the libraries they use.

However, `GCPlaceholderTextView` doesn't have any version tags. The current HEAD commit has been added as version 0.0.1, but a version tag will make dependency resolution much easier.

[Semantic version](http://semver.org) tags (instead of plain commit hashes/revisions) allow for [resolution of cross-dependencies](https://github.com/CocoaPods/Specs/wiki/Cross-dependencies-resolution-example).

In case you didn’t know this yet; you can tag the current HEAD as, for instance, version 1.0.0, like so:

```
$ git tag -a 1.0.0 -m "Tag release 1.0.0"
$ git push --tags
```

**Comment by dbgrandi** [comment]
So, is that a no? This would really be helpful.

**Comment by gcamp** [comment]
Sorry I thought this would be needed only for future revisions. Pushed the 1.0 now, and will be updating when needed.

**Comment by dbgrandi** [comment]
Thanks, @gcamp!

I just made a [pull-request](https://github.com/CocoaPods/Specs/pull/1187) to add 1.0.0 to CocoaPods
